<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Formadmission extends Model
{
    protected $table = "formsadmissions";
    protected $primaryKey = "fmId";
    protected $fillable = [
        'foto',
        'nombres',
        'apellidos',
        'genero',
        'fechanacimiento',
        'tipodocumento',
        'numerodocumento',
        'nacionalidad',
        'mesesgestacion',
        'tiposangre',
        'tipoparto',
        'enfermedades',
        'tratamientos',
        'alergias',
        'asistenciaterapias',
        'cual',
        'health',
        'programa',
        'numerohermanos',
        'lugarqueocupa',
        'conquienvive',
        'otroscuidados',
        'nombreacudiente1',
        'docacu1',
        'documentoacudiente1',
        'direccionacudiente1',
        'barrioacudiente1',
        'localidadacudiente1',
        'celularacudiente1',
        'whatsappacudiente1',
        'correoacudiente1',
        'formacionacudiente1',
        'tituloacudiente1',
        'tipoocupacionacudiente1',
        'empresaacudiente1',
        'direccionempresaacudiente1',
        'ciudadempresaacudiente1',
        'barrioempresaacudiente1',
        'localidadempresaacudiente1',
        'cargoempresaacudiente1',
        'fechaingresoempresaacudiente1',
        'rhacu1',
        'sexoacudiente1',
        'nombreacudiente2',
        'docacu2',
        'documentoacudiente2',
        'direccionacudiente2',
        'barrioacudiente2',
        'localidadacudiente2',
        'celularacudiente2',
        'whatsappacudiente2',
        'correoacudiente2',
        'formacionacudiente2',
        'tituloacudiente2',
        'tipoocupacionacudiente2',
        'empresaacudiente2',
        'direccionempresaacudiente2',
        'ciudadempresaacudiente2',
        'barrioempresaacudiente2',
        'localidadempresaacudiente2',
        'cargoempresaacudiente2',
        'fechaingresoempresaacudiente2',
        'rhacu2',
        'sexoacudiente2',
        'nombreemergencia',
        'documentoemergencia',
        'direccionemergencia',
        'barrioemergencia',
        'localidademergencia',
        'celularemergencia',
        'whatsappemergencia',
        'parentescoemergencia',
        'correoemergencia',
        'nombreautorizado1',
        'documentoautorizado1',
        'parentescoautorizado1',
        'nombreautorizado2',
        'documentoautorizado2',
        'parentescoautorizado2',
        'fechaingreso',
        'firmaacudiente1',
        'firmaacudiente2',
        'status',
        'migracion',
        // Actualizacion 10 de Septiembre del 2020
        // INFORMACION Y EXPECTATIVAS
        'expectatives_likechild',
        'expectatives_activityschild',
        'expectatives_toychild',
        'expectatives_aspectchild',
        'expectatives_dreamforchild',
        'expectatives_learnchild',
        // INFORMACION CULTURAL
        'cultural_eventfamily',
        'cultural_supportculturefamily',
        'cultural_gardenlearnculture',
        'cultural_aspectchild',
        'cultural_dreamforchild',
        'cultural_shareculturefamily'
    ];
    public $timestamps = false;
}
